### ISSUE TITLE
Spice up the readme

### ISSUE THREAD

**Issue by johndbritton** [johndbritton/osaka#1]
It'd be great to have a photo of Osaka in the readme.

@dice do you have any suggestions?

**Comment by johndbritton** [comment]
Maybe this one
![image](https://cloud.githubusercontent.com/assets/123345/8147269/02c21382-129d-11e5-92d6-e701e32749cb.png)

**Comment by dice** [comment]
What about these @johndbritton ?
![dsc_1936](https://cloud.githubusercontent.com/assets/676836/8147272/11330ca0-129d-11e5-93c5-efa3183c4bc0.JPG)
![dsc_1937](https://cloud.githubusercontent.com/assets/676836/8147271/1131809c-129d-11e5-9ae5-613cf0dfcb81.JPG)
